[platformio]
src_dir = studio
default_envs = cardenza
[env:cardputer-adv]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = m5stack-stamps3
framework = arduino
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv
board_build.flash_mode = qio
board_build.f_flash = 80000000L
build_flags = -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps = lovyan03/LovyanGFX@1.2.19
[env:cardenza]
extends = env:cardputer-adv
board_build.arduino.memory_type = qio_qspi
build_flags = ${env:cardputer-adv.build_flags} -DCARDENZA_TARGET=1 -Wl,--wrap=esp_partition_erase_range
